name: 'Continuous Delivery'

on:
  push:
    branches: [main]

env:
  SERVICE_NAME: flight-delay-api
  REGION: us-central1

jobs:
  deploy:
    # Skip deploy if GCP secrets are missing (prevents failures without billing)
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    if: ${{ env.GCP_PROJECT_ID != '' && env.GCP_SA_KEY != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud project
        run: gcloud config set project ${{ env.GCP_PROJECT_ID }}

      - name: Build image with Cloud Build
        run: gcloud builds submit --tag gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} --platform managed \
            --allow-unauthenticated --port 8080